project_id = "pxsqflzlsghvbalozynz"

[functions.submit-contact]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.create-employee]
verify_jwt = false

[functions.totp-setup]
verify_jwt = false
